# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [push, pull_request]
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #branches: [ master ]
  #pull_request:
  #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-commit-message:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check jira ticket and module
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?:(?:Revert \")?[A-Z]{3,10}-\d{1,6}: [a-z0-9\/\-\_]{2,16}: .+?)|(?:Merge .+?)$'
          flags: 'g'
          error: 'Your first line has to contain a jira ticket id and module or it needs to start with Merge(e.g.: "ESW-1234: dnsmasq: Commit message")'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if double new line after title
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(?:^(?:Revert \")?[A-Z]{3,10}-\d{1,6}: [a-z0-9\/\-]{2,16}: .+?$\n\n\S)|(?:^Merge \S)'
          flags: 'gm'
          error: 'Double new line missing after title'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
          excludeTitle: 'true'
      - name: Check line length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^#].{0,72}$'
          flags: 'gm'
          error: 'Max line length is 72 characters'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
      - name: Check commit signature
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(?:\n\nSigned-off-by: .+? <.+?@.+?>$)|(?:^Merge)'
          flags: 'gm'
          error: 'Commit is not signed(Use: "git commit -s" to sign commit)'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
          excludeTitle: 'true'
