# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  - check-commit-message-1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check if PR title contains jira ticket and module
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?:(?:Revert \")?[A-Z]{3,10}-\d{1,6}: .+?)|(?:Merge .+?)$'
          flags: 'g'
          error: 'PR title has to start with jira ticket id or Merge(e.g.: "ESW-1234: PR title" or "Merge pull request...")'
          excludeDescription: 'true'

  # This workflow contains a single job called "build"
  - check-commit-message-2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check jira ticket and module
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?:(?:Revert \")?[A-Z]{3,10}-\d{1,6}: .+?)|(?:Merge .+?)$'
          flags: 'g'
          error: 'Commit title has to start with jira ticket id or Merge(e.g.: "ESW-1234: Commit title" or "Merge pull request...")'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
          excludeTitle: 'true'

  # This workflow contains a single job called "build"
  - check-commit-message-3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check if double new line after title
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(?:^(?:Revert \")?[A-Z]{3,10}-\d{1,6}: .+?$\n\n\S)|(?:^Merge \S)'
          flags: 'gm'
          error: 'Double new line missing after title'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
          excludeTitle: 'true'

  # This workflow contains a single job called "build"
  - check-commit-message-4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check line length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^#].{0,72}$'
          flags: 'gm'
          error: 'Max line length is 72 characters'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'

  # This workflow contains a single job called "build"
  - check-commit-message-5:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check commit signature
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(?:\n\nSigned-off-by: .+? <.+?@.+?>$)|(?:^Merge)'
          flags: 'gm'
          error: 'Commit is not signed(Use: "git commit -s" to sign commit)'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
          excludeTitle: 'true'
